name: Build and Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=20.0.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [preview, production]
        include:
          - environment: preview
            branch: develop
          - environment: production
            branch: master
    if: github.ref == 'refs/heads/${{ matrix.branch }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ matrix.environment }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          if [ ${{ matrix.environment }} == "preview" ]; then
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          if [ ${{ matrix.environment }} == "preview" ]; then
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
