name: CI/CD Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - master
      - develop
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=20.0.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

  deploy_preview:
    needs: build_and_test
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/vercel-deploy.yml@develop
    with:
      environment: preview
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
    if: github.ref == 'refs/heads/develop'

  deploy_prod:
    needs: build_and_test
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/vercel-deploy.yml@master
    with:
      environment: production
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
    if: github.ref == 'refs/heads/master'

https://github.com/jazmindestefano/tpi-frontend-app/blob/develop/.github/workflows/ci.yml