name: CI Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: [opened, synchronize, reopened]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=20.0.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

  deploy_preview:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Set environment to preview
        run: echo "ENVIRONMENT=preview" >> $GITHUB_ENV

      - name: Check Vite installation
        run: npx vite --version

      - name: Deploy to Vercel
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          npx vite build --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  deploy_prod:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Set environment to production
        run: echo "ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Check Vite installation
        run: npx vite --version

      - name: Deploy to Vercel
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          npx vite build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
