name: Vercel Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      vercel_token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ secrets.vercel_token }}

      - name: Build Project Artifacts
        run: vercel build ${{ inputs.environment == 'production' && '--prod' || '' }} --token=${{ secrets.vercel_token }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt ${{ inputs.environment == 'production' && '--prod' || '' }} --token=${{ secrets.vercel_token }}